name = "NLPModelsKnitro"
uuid = "bec4dd0d-7755-52d5-9a02-22f0ffc7efcb"
authors = ["Dominique Orban <dominique.orban@gmail.com>"]
version = "0.1.0"

[deps]
KNITRO = "67920dd8-b58e-52a8-8622-53c4cffbe346"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"

[compat]
KNITRO = "≥ 0.6.0"
NLPModels = "0.8.0, 0.9"
SolverTools = "≥ 0.1.4"
julia = "^1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
